#!/usr/bin/env bash
#
# gen-copilot-instructions.sh — генерирует .github/copilot-instructions.md
# из AGENTS.md. Один источник правды (AGENTS.md) → производный формат для
# GitHub Copilot Workspace / Copilot Chat / Copilot Code Review.
#
# Использование:
#   scripts/gen-copilot-instructions.sh              # сгенерировать / обновить
#   scripts/gen-copilot-instructions.sh --check      # проверить актуальность без записи; exit 1 если расходится
#
# Аналог scripts/gen-cursor-rules.sh, но другая логика:
# - gen-cursor-rules: SKILL.md → .cursor/rules/<skill>.mdc (по одной обёртке на skill).
# - gen-copilot-instructions: AGENTS.md → .github/copilot-instructions.md (один файл).
#
# См. ADR https://github.com/msamichev/methodology-ai/blob/main/docs/adr/20260522-1900-gen-copilot-instructions-for-cross-vendor-coverage.md
#

set -euo pipefail

# Pre-check: python3 ≥ 3.8.
if ! command -v python3 >/dev/null 2>&1; then
  echo "✗ gen-copilot-instructions: требуется python3 (не найден в PATH)." >&2
  echo "  Установка: macOS — 'brew install python3'; Linux — пакет 'python3'." >&2
  exit 127
fi
if ! python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 8) else 1)' 2>/dev/null; then
  PY_VER="$(python3 --version 2>&1 || echo unknown)"
  echo "✗ gen-copilot-instructions: требуется Python 3.8+ (найден: $PY_VER)." >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

MODE="${1:-generate}"

SOURCE="AGENTS.md"
OUTPUT=".github/copilot-instructions.md"

if [[ ! -f "$SOURCE" ]]; then
  echo "✗ Не найден $SOURCE — нечего конвертировать." >&2
  exit 1
fi

python3 - "$SOURCE" "$OUTPUT" "$MODE" <<'PY'
from __future__ import annotations
import re
import sys
from pathlib import Path

source = Path(sys.argv[1])
output = Path(sys.argv[2])
mode = sys.argv[3]

agents_text = source.read_text(encoding="utf-8")


def extract_section(text: str, start_pattern: str, stop_pattern: str) -> str:
    """Извлекает блок markdown между двумя regex-границами (start включается, stop — нет)."""
    m_start = re.search(start_pattern, text, re.MULTILINE)
    if not m_start:
        return ""
    start = m_start.start()
    m_stop = re.search(stop_pattern, text[m_start.end():], re.MULTILINE)
    end = m_start.end() + m_stop.start() if m_stop else len(text)
    return text[start:end].strip()


# §0 — Project one-liner
section_0 = extract_section(
    agents_text,
    r"^## 0\. Project one-liner",
    r"^---\s*$",
)

# §4.4 Безопасность — до начала §4.5 (### 4.5) или до конца §4 (---)
section_44 = extract_section(
    agents_text,
    r"^### 4\.4 ",
    r"^### 4\.5 |^---\s*$",
)

# §5 — до §6
section_5 = extract_section(
    agents_text,
    r"^## 5\. Правила работы AI-ассистента",
    r"^## 6\. ",
)

# §6 — до §6.1 (Autonomous mode подсекция) или до §7
section_6 = extract_section(
    agents_text,
    r"^## 6\. Триггерные команды",
    r"^### 6\.1 |^## 7\. ",
)


generated = f"""<!--
  AUTOGENERATED from AGENTS.md by scripts/gen-copilot-instructions.sh.
  DO NOT EDIT MANUALLY — изменения исчезнут при следующей генерации.
  Источник правды — AGENTS.md в корне репозитория.
  Регенерация: bash scripts/gen-copilot-instructions.sh
-->

# GitHub Copilot Workspace — Instructions

Этот файл — производный от `AGENTS.md` для GitHub Copilot Workspace, Copilot Chat и Copilot Code Review. Полный контракт с правилами и командами — в `AGENTS.md`. Этот файл — короткая выжимка, потому что Copilot Workspace не поддерживает auto-trigger по семантике (как Claude Code skills или Cursor rules с path-scoping) и работает по статическим инструкциям.

Что важно для Copilot при работе с этим проектом:

---

{section_0}

---

{section_5}

---

{section_44}

---

{section_6}

---

## Источники для глубокого чтения

- [`AGENTS.md`](../AGENTS.md) — канонический контракт для AI-агента (источник правды).
- [`METHODOLOGY.md`](../METHODOLOGY.md) — обзор методологии для людей.
- [`playbooks/README.md`](../playbooks/README.md) — индекс всех команд и универсальных процедур.
- [`docs/adr/`](../docs/adr/) — Architecture Decision Records.

## Как этот файл регенерируется

При изменении `AGENTS.md` запустить:

```bash
bash scripts/gen-copilot-instructions.sh
```

Проверить актуальность (для CI):

```bash
bash scripts/gen-copilot-instructions.sh --check
```

`--check` возвращает exit 1, если `.github/copilot-instructions.md` расходится с тем, что сейчас сгенерировал бы скрипт.
"""

if mode == "--check":
    if not output.exists():
        print(f"✗ {output} не существует. Запусти: bash scripts/gen-copilot-instructions.sh")
        sys.exit(1)
    existing = output.read_text(encoding="utf-8")
    if existing.strip() != generated.strip():
        print(f"✗ {output} расходится с AGENTS.md. Запусти: bash scripts/gen-copilot-instructions.sh")
        sys.exit(1)
    print(f"✓ {output} в актуальном состоянии.")
    sys.exit(0)

# generate mode
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text(generated, encoding="utf-8")
print(f"✓ Сгенерирован {output} ({len(generated)} символов).")
PY
